### ISSUE TITLE
Plugin uses only a single processor / core for compilation

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-em-atomstructutils#23]
Version 3.0.3
Installation via the Plugin manager
Number of processors: set to 4

Expected behavior: 4 cores will be used for compilation

Actual behavior: only single core is used for compilation

**Comment by rmarabini** [comment]
I guess you refer to maxit program (no other source is compiled here). As far as I know maxit does not support compilation with several CPUs
